export { default as Nav } from './Nav/Nav'
export { default as Intro } from './Intro/Intro'
export { default as About } from './About/About'
export { default as Skills } from './Skills/Skills'
export { default as Contact } from './Contact/Contact'
